[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build='make'


[[plugins]]
repo = 'mattn/emmet-vim'
hook_add = '''
let g:user_emmet_settings = {
\ 'variables' : {
\ 'lang' : "ja"
\ },
\ 'html' : {
\   'indentation' : ' ',
\   'snippets' : {
\    'html:5':"<!DOCTYPE html>\n"
\      ."<html lang=\"${lang}\>\n"
\      ."<head>\n"
\      ."\t<meta charset=\"${charset}\">\n"
\      ."\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\>\n"
\      ."\t<title></title>\n"
\      ."</head>\n"
\      ."<body>\n\t${child}|\n</body>\n"
\      ."</html>",
\}
\}
\}
let g:user_emmet_leader_key='<c-z>'
'''


[[plugins]]
repo = 'scrooloose/nerdtree'




[[plugins]]
repo = 'tpope/vim-surround'








[[plugins]]
repo = 'tpope/vim-fugitive'
hook_source ='''
source ./plugins/fugitive.rc.vim
'''



[[plugins]]
repo = 'vim-airline/vim-airline.git'

[[plugins]]
repo = 'vim-airline/vim-airline-themes.git'

[[plugins]]
repo = 'ryanoasis/vim-devicons'

[[plugins]]
repo='Yggdroot/indentLine'
hook_source='''
source ./plugins/indent.rc.vim
'''


[[plugins]]
repo = 'cohama/lexima.vim'


[[plugins]]
repo = 'tpope/vim-commentary'
