[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neomru.vim'
on_source = ['unite.vim']


[[plugins]]
repo = 'nvie/vim-flake8'
on_ft = ['python']
max-line-length=100

[[plugins]]
repo = 'psf/black'

on_ft=['python']




[[plugins]]
repo = 'elzr/vim-json'
on_ft = ['json']



[[plugins]]
repo = 'thinca/vim-quickrun'
on_ft = ['javascript', 'python']
hook_add='''
let g:quickrun_config={}

let g:quickrun_config._ = {
  \ 'outputter/error/success': 'buffer',
  \ 'outputter/error/error': 'quickfix',
  \ 'hook/time/enable': 1,
  \ '*': {'split': ''},
  \ }
  set splitbelow

  '''





[[plugins]]
repo = 'hokaccha/vim-html5validator'
on_ft=['html']

[[plugins]]
repo = 'mattn/sonictemplate-vim'
on_ft=['html']
hook_add = '''
let g:sonictemplate_vim_template_dir = [
  \ '~/.config/nvim/userconfig/template'
  \]
  '''

[[plugins]]
repo = "neoclide/coc.nvim"
on_ft=["python", "javascript", "javascriptreact"]
merge = 0
rev = "release"
hook_add = """
source ~/.config/nvim/userconfig/plugins/coc.rc.vim
"""
